const INC_COUNTER = "INC_COUNTER";
const ADD_COUNTER = "ADD_COUNTER";
const DEC_COUNTER = "DEC_COUNTER";
const SUB_COUNTER = "SUB_COUNTER";
const STORE_RESULT = "STORE_RESULT";
const DELETE_RESULT = "DELETE_RESULT";